# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXzstiLKFcQ-oCrXY-oP86vm-tH095pE
"""

!pip install marker-pdf -q
!pip install "Pillow<10.3.0" -q

import json
import os
import re
import shutil
import sys
import traceback
from pathlib import Path

# ---------------------------------------------------------------------------
# Configuration — edit these if your Drive layout differs
# ---------------------------------------------------------------------------

DRIVE_ROOT      = "/content/drive/MyDrive/ncert_pdfs"   # root of your PDFs
OUTPUT_ROOT = "/content/drive/MyDrive/extraction_results"         # where JSONs are saved
ZIP_PATH        = "/content/drive/MyDrive/extraction_results_2"          # zip saved here

# Folder names under DRIVE_ROOT that you want to process.
# Set to None to process everything recursively.
SUBJECT_FOLDERS = [
    "class_11_phy",
    "class_12_chem",
    "class_12_bio",
    "class_12_phy",

]

# Marker config — reasonable defaults for Colab T4
MARKER_CONFIG = {
    "output_format": "json",   # gives us exact per-page structure — do not change
    "langs": ["en"],
    "disable_image_extraction": True,
}

os.makedirs(OUTPUT_ROOT, exist_ok=True)
print("Output directory:", OUTPUT_ROOT)

from google.colab import drive
drive.mount("/content/drive")

# Quick sanity check
if not os.path.isdir(DRIVE_ROOT):
    raise FileNotFoundError(
        f"Drive root not found: {DRIVE_ROOT}\n"
        "Check that your Drive is mounted and DRIVE_ROOT is correct."
    )

pdfs = list(Path(DRIVE_ROOT).rglob("*.pdf"))
print(f"Found {len(pdfs)} PDFs under {DRIVE_ROOT}")
for p in pdfs:
    print(" ", p.relative_to(DRIVE_ROOT))

from marker.converters.pdf import PdfConverter
from marker.models import create_model_dict
from marker.config.parser import ConfigParser

print("Loading Marker models … (downloads ~1 GB on first run, cached after)")
artifact_dict = create_model_dict()
print("Models loaded.")

config_parser = ConfigParser(MARKER_CONFIG)
converter = PdfConverter(
    config=config_parser.generate_config_dict(),
    artifact_dict=artifact_dict,
    processor_list=config_parser.get_processors(),
    renderer=config_parser.get_renderer(),
)
print("PdfConverter ready.")

def _extract_equations_from_block(block: dict) -> list[str]:
    """
    Recursively collect Equation blocks and TextInlineMath blocks from the
    Marker JSON tree.  Returns a deduplicated list of LaTeX strings.
    """
    seen: set[str] = set()
    results: list[str] = []

    def _walk(node: dict):
        btype = node.get("block_type", "")
        if btype in ("Equation", "TextInlineMath"):
            # html field contains the LaTeX wrapped in <math> or similar tags
            html = node.get("html", "")
            # strip any HTML tags to get raw LaTeX
            latex = re.sub(r"<[^>]+>", "", html).strip()
            if latex and latex not in seen:
                seen.add(latex)
                results.append(latex)
        for child in node.get("children") or []:
            _walk(child)

    _walk(block)
    return results


def _blocks_to_plain_text(children: list[dict]) -> str:
    """
    Convert a page's children list to plain text by stripping HTML tags
    from the html field of each block.  Preserves reading order (children
    are already in document order).

    Skips PageHeader and PageFooter blocks — we don't want running headers
    polluting the text that goes into the parser.
    """
    SKIP_TYPES = {"PageHeader", "PageFooter"}
    lines: list[str] = []

    def _walk(node: dict):
        btype = node.get("block_type", "")
        if btype in SKIP_TYPES:
            return
        html = node.get("html", "")
        if html:
            # If it's a list item, prepend a bullet/dash to preserve list formatting
            if "<li" in html:
                text = re.sub(r"</(p|div|h[1-6]|tr|td|th)>", "\n", html)
                text = re.sub(r"<li[^>]*>", "- ", text)  # Prepend dash to list items
                text = re.sub(r"</li>", "\n", text)
            else:
                # Replace block-level tags with newlines, strip the rest
                text = re.sub(r"</(p|div|h[1-6]|li|tr|td|th)>", "\n", html)
            
            text = re.sub(r"<br\s*/?>", "\n", text)
            text = re.sub(r"<[^>]+>", "", text)
            text = re.sub(r"&amp;", "&", text)
            text = re.sub(r"&lt;", "<", text)
            text = re.sub(r"&gt;", ">", text)
            text = re.sub(r"&nbsp;", " ", text)
            text = text.strip()
            if text:
                lines.append(text)
        # recurse into children only if the node itself had no html
        # (leaf nodes carry html; container nodes carry children)
        elif node.get("children"):
            for child in node["children"]:
                _walk(child)

    for block in children:
        _walk(block)

    return "\n".join(lines)


def marker_json_to_extraction_result(rendered, pdf_path: str) -> dict:
    """
    Convert the Marker 1.x JSON-format rendered output into the
    ExtractionResult-compatible dict that ExtractionResult.from_json() reads.

    Why JSON output_format (not markdown)?
    - JSON output gives us one list item per page — exact page boundaries,
      no heuristic splitting on '---'.
    - Each page's block_type="Page" node has all children in reading order.
    - page_id in the block id encodes the 0-indexed page number reliably.

    The rendered object (when output_format="json") has:
        rendered.children  — list of Page-level dicts
        rendered.metadata  — dict with page_stats list
    """
    # rendered.children is the top-level list of Page blocks
    rendered = rendered.model_dump()

    page_blocks: list[dict] = rendered["children"]

    metadata = rendered.get("metadata", {})
    page_stats: list[dict] = metadata.get("page_stats", [])

    # Build a lookup: 0-indexed page_id → text_extraction_method
    extraction_method_by_page: dict[int, str] = {
        int(ps["page_id"]): ps.get("text_extraction_method", "unknown")
        for ps in page_stats
        if "page_id" in ps
    }

    pages = []
    has_equations = False
    has_tables = False

    for page_block in page_blocks:
        # Extract 0-indexed page number from block id: "/page/10/Page/366" → 10
        block_id: str = page_block.get("id", "")
        m = re.search(r"/page/(\d+)/", block_id)
        page_idx = int(m.group(1)) if m else len(pages)
        page_no = page_idx + 1  # convert to 1-indexed

        children = page_block.get("children") or []

        plain_text = _blocks_to_plain_text(children)
        equations  = _extract_equations_from_block(page_block)

        # Detect tables: any child with block_type in table types
        def _has_table(node: dict) -> bool:
            if node.get("block_type") in ("Table", "TableGroup"):
                return True
            return any(_has_table(c) for c in (node.get("children") or []))
        page_has_table = any(_has_table(c) for c in children)

        if equations:
            has_equations = True
        if page_has_table:
            has_tables = True

        pages.append({
            "page_no": page_no,
            "text": plain_text,
            "markdown": None,   # not needed downstream; saves space in JSON
            "equations": equations,
            "_extraction_method": extraction_method_by_page.get(page_idx, "unknown"),
        })

    # Detect language from metadata if present
    language = metadata.get("language", None)

    return {
        "extraction_backend": "marker",
        "language": language,
        "has_equations": has_equations,
        "has_tables": has_tables,
        "source_pdf": str(pdf_path),
        "pages": pages,
    }


def output_path_for(pdf_path: Path, drive_root: Path, output_root: Path) -> Path:
    """
    Mirror the Drive folder structure under output_root.
    e.g. .../class_11_chem/ch01.pdf → output_root/class_11_chem/ch01.json
    """
    relative = pdf_path.relative_to(drive_root)
    out = output_root / relative.with_suffix(".json")
    out.parent.mkdir(parents=True, exist_ok=True)
    return out


def already_done(out_path: Path) -> bool:
    """
    Skip files that were successfully processed in a previous run.
    A file is considered done if the JSON exists and is valid.
    """
    if not out_path.exists():
        return False
    try:
        with open(out_path) as f:
            data = json.load(f)
        return bool(data.get("pages"))
    except Exception:
        return False

drive_root  = Path(DRIVE_ROOT)
output_root = Path(OUTPUT_ROOT)

# Collect PDFs to process
if SUBJECT_FOLDERS:
    pdf_list = []
    for folder in SUBJECT_FOLDERS:
        folder_path = drive_root / folder
        if folder_path.is_dir():
            pdf_list.extend(folder_path.rglob("*.pdf"))
        else:
            print(f"[WARN] Folder not found: {folder_path}")
else:
    pdf_list = list(drive_root.rglob("*.pdf"))

pdf_list = sorted(pdf_list)

total = len(pdf_list)
print(f"\nTotal PDFs to process: {total}")

results_log = []   # accumulates {file, status, pages, error} for summary

for idx, pdf_path in enumerate(pdf_list, 1):
    out_path = output_path_for(pdf_path, drive_root, output_root)
    rel = pdf_path.relative_to(drive_root)

    print(f"\n[{idx}/{total}] {rel}")

    if already_done(out_path):
        print("  → already done, skipping")
        results_log.append({"file": str(rel), "status": "skipped"})
        continue

    try:
        rendered = converter(str(pdf_path))
        result_dict = marker_json_to_extraction_result(rendered, pdf_path)

        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(result_dict, f, ensure_ascii=False, indent=2)

        n_pages = len(result_dict["pages"])
        has_eq  = result_dict["has_equations"]
        print(f"  → saved {n_pages} pages  equations={has_eq}  → {out_path.name}")
        results_log.append({
            "file": str(rel),
            "status": "ok",
            "pages": n_pages,
            "has_equations": has_eq,
        })

    except Exception as e:
        print(f"  [ERROR] {e}")
        traceback.print_exc()
        results_log.append({"file": str(rel), "status": "error", "error": str(e)})
        # Write a stub so already_done() returns False next run
        if out_path.exists():
            out_path.unlink()

# Print summary
print("\n" + "="*60)
print("EXTRACTION SUMMARY")
print("="*60)
ok      = [r for r in results_log if r["status"] == "ok"]
skipped = [r for r in results_log if r["status"] == "skipped"]
errors  = [r for r in results_log if r["status"] == "error"]
print(f"  Processed : {len(ok)}")
print(f"  Skipped   : {len(skipped)}")
print(f"  Errors    : {len(errors)}")
if errors:
    print("\nFailed files:")
    for r in errors:
        print(f"  {r['file']} — {r.get('error', '')}")

# Save log
log_path = output_root / "extraction_log.json"
with open(log_path, "w") as f:
    json.dump(results_log, f, indent=2)
print(f"\nLog saved → {log_path}")

# %%
# Pick the first successfully extracted file and do a quick sanity check.
# This verifies the JSON is readable by ExtractionResult.from_json() before
# you download anything.

sample = next(
    (output_root / r["file"].replace(".pdf", ".json")
     for r in results_log if r["status"] == "ok"),
    None
)

if sample and sample.exists():
    with open(sample) as f:
        data = json.load(f)

    print(f"Sample file : {sample.name}")
    print(f"Backend     : {data['extraction_backend']}")
    print(f"Pages       : {len(data['pages'])}")
    print(f"Has eqs     : {data['has_equations']}")
    print(f"Has tables  : {data['has_tables']}")
    print(f"\nPage 1 text preview (first 300 chars):")
    print(data["pages"][0]["text"][:300])
    print(f"\nPage 1 equations: {data['pages'][0]['equations'][:3]}")

    # Verify page numbering is contiguous (catches split failures)
    page_nos = [p["page_no"] for p in data["pages"]]
    expected = list(range(1, len(page_nos) + 1))
    if page_nos == expected:
        print("\n✓ Page numbering is contiguous and correct")
    else:
        print(f"\n[WARN] Page numbering gaps detected: {page_nos[:10]}…")
else:
    print("No successfully extracted files to validate.")

from google.colab import files

zip_output = shutil.make_archive(ZIP_PATH, "zip", OUTPUT_ROOT)
zip_size_mb = os.path.getsize(zip_output) / 1024 / 1024
print(f"Zip created: {zip_output}  ({zip_size_mb:.1f} MB)")
files.download(zip_output)

import os
os.makedirs("/content/drive/MyDrive/extraction_results", exist_ok=True)