import re
from typing import Optional
from src.extraction.base_parser import BaseParser

# Maharashtra specific running headers
_MAHA_HEADER_RES = [
    re.compile(r'^Maharashtra\s*State\s*Bureau.*$', re.MULTILINE | re.IGNORECASE),
]

SECTION_RE = re.compile(r'^(\d{1,2}\.\d{1,2}(?:\.\d{1,2})?)\s+([A-Za-z].+?)\s*$')

# Maharashtra semantic blocks
RECALL_RE = re.compile(r'^(?:Can\s+you\s+recall\??|Can\s+you\s+tell\??|Think\s+about\s+it\??)\s*$', re.IGNORECASE)
DO_YOU_KNOW_RE = re.compile(r'^Do\s+you\s+know\??\s*$', re.IGNORECASE)
INTERNET_FRIEND_RE = re.compile(r'^Internet\s*my\s*friend\??\s*$', re.IGNORECASE)
FIND_OUT_RE = re.compile(r'^Find\s+out\??\s*$', re.IGNORECASE)
SCIENTIST_RE = re.compile(r'^Know\s+the\s+scientists?\s*$', re.IGNORECASE)
EXERCISE_RE = re.compile(r'^Exercises?\s*$', re.IGNORECASE)

# Inside Exercise splits
MCQ_RE = re.compile(r'^(?:Q\.\s*\d+\.\s*)?(?:Multiple\s+Choice|Choose\s+the\s+correct)', re.IGNORECASE)
SUBJECTIVE_RE = re.compile(r'^(?:Q\.\s*\d+\.\s*)?(?:Answer\s+the\s+following|Answer\s+in\s+brief|Write\s+short\s+notes)', re.IGNORECASE)
PROJECT_RE = re.compile(r'^(?:Project|Project\s+Work)\s*$', re.IGNORECASE)

class MahaParser(BaseParser):
    def preprocess_pages(self, pages: list[dict]) -> list[dict]:
        pages = super().preprocess_pages(pages)
        for page in pages:
            text = page.get("text", "")
            for pat in _MAHA_HEADER_RES:
                text = pat.sub('', text)
            
            # Remove non-ascii noise often generated by Marker for Maha books
            # Retain standard ascii, degrees °, newlines
            text = re.sub(r'[^\x00-\x7F\°\n\u201C\u201D\u2018\u2019\–\—]', ' ', text)
            
            page["text"] = self.clean_text(text)
        return pages

    def detect_numbered_section(self, line: str) -> Optional[tuple]:
        line = line.strip()
        m = SECTION_RE.match(line)
        if m:
            no = m.group(1).rstrip('.')
            title = m.group(2).strip()
            return no, title
        return None

    def find_figure_references(self, text: str) -> list[str]:
        # Matches "Fig 1.1", "Fig. 1.2a", "Figure 3.4"
        refs = re.findall(r'(?:Fig\.|Figure)\s*(\d+\.\d+[a-z]?)', text, re.IGNORECASE)
        # return standardized "IMG_<ch_no>_<ref>" or just the raw reference so multimodal merge can resolve it later
        # We will just return the raw string like "1.1" so it can be matched with image_caption or image_id later
        return list(set(refs))

    def process_pages_to_chunks(self, pages: list[dict]) -> list[dict]:
        lines = self.pages_to_lines(pages)
        eq_map = self.get_equations_by_page(pages)

        chunks = []
        chunk_id_counter = [0]

        current_section_no = None
        current_section_title = None
        current_subsection_no = None
        current_subsection_title = None

        current_lines: list[dict] = []
        current_page_start = pages[0]["page_no"] if pages else 1
        current_page_end = current_page_start
        current_mode = "content"

        def flush_chunk():
            nonlocal current_page_start
            text = self.clean_text('\n'.join(l["text"] for l in current_lines))
            if len(text.strip()) < 30:
                current_lines.clear()
                return

            chunk_equations = list(eq_map.get(current_page_end, []))
            chunk_id = self.generate_chunk_id(chunk_id_counter, current_section_no)
            figure_refs = self.find_figure_references(text)

            mapped_type = current_mode
            if current_mode == "content":
                mapped_type = "explanation"

            chunks.append({
                "chunk_id":       chunk_id,
                "source":         self.source,
                "subject":        self.subject,
                "chapter_no":     self.chapter_no,
                "chapter_title":  self.chapter_title,
                "section":        current_section_title,
                "section_no":     current_section_no,
                "subsection":     current_subsection_title,
                "subsection_no":  current_subsection_no,
                "chunk_type":     mapped_type,
                "text":           text,
                "equations":      chunk_equations,
                "page_start":     current_page_start,
                "page_end":       current_page_end,
                "figure_references": figure_refs
            })
            current_lines.clear()
            current_page_start = current_page_end

        in_exercise_mode = False

        for line_obj in lines:
            line = line_obj["text"].strip()
            page_no = line_obj["page_no"]
            current_page_end = page_no

            detected = self.detect_numbered_section(line)
            if detected and not in_exercise_mode:
                flush_chunk()
                current_mode = "content"
                no, title = detected
                if no.count('.') == 1:
                    current_section_no, current_section_title = no, title
                    current_subsection_no, current_subsection_title = None, None
                elif no.count('.') >= 2:
                    current_subsection_no, current_subsection_title = no, title
                current_page_start = page_no
                continue

            # Special semantic blocks
            if RECALL_RE.match(line):
                flush_chunk()
                current_mode = "recall"
                current_page_start = page_no
                continue

            if DO_YOU_KNOW_RE.match(line):
                flush_chunk()
                current_mode = "explanation" # or could be activity
                current_page_start = page_no
                continue
                
            if INTERNET_FRIEND_RE.match(line):
                flush_chunk()
                current_mode = "internet_task"
                current_page_start = page_no
                continue

            if FIND_OUT_RE.match(line):
                flush_chunk()
                current_mode = "activity"
                current_page_start = page_no
                continue

            if SCIENTIST_RE.match(line):
                flush_chunk()
                current_mode = "scientist_box"
                current_page_start = page_no
                continue

            if EXERCISE_RE.match(line):
                flush_chunk()
                in_exercise_mode = True
                current_mode = "exercise"
                current_page_start = page_no
                continue
                
            if in_exercise_mode:
                if MCQ_RE.match(line):
                    flush_chunk()
                    current_mode = "mcq"
                    current_page_start = page_no
                elif SUBJECTIVE_RE.match(line):
                    flush_chunk()
                    current_mode = "exercise"
                    current_page_start = page_no
                elif PROJECT_RE.match(line):
                    flush_chunk()
                    current_mode = "project"
                    current_page_start = page_no

            current_lines.append(line_obj)

        flush_chunk()
        return chunks

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--subject", default="Biology")
    parser.add_argument("--source", default="MAHA")
    parser.add_argument("--chapter_no", type=int, default=1)
    args = parser.parse_args()
    
    mp = MahaParser(
        subject=args.subject,
        source=args.source,
        chapter_no=args.chapter_no,
        chapter_title=""
    )
    mp.parse(args.input, args.output)
    print(f"Parsed MAHA chapter into {args.output}")
